SELECT * FROM cust_ci;
SELECT CSTNAME_VALUE, CSTNAME_EFCTV_DATE FROM CUST_NAME WHERE CSTNAME_CLS_ID = 1;
SELECT * FROM CUST_NAME ORDER BY CSTNAME_EFCTV_DATE DESC;
UPDATE CUST_NAME SET CSTNAME_VALUE = 'Ram Kumar' WHERE CST_ID = 1001;
UPDATE CUST_NAME SET CSTNAME_VALUE = 'John Smith', CSTNAME_EFCTV_DATE = '2025-03-01' WHERE CST_ID = 1002;
UPDATE CUST_NAME SET CSTNAME_CRUD_VALUE = 'U' WHERE CSTNAME_CLS_ID = 2;
DELETE FROM CUST_NAME WHERE CSTNAME_CLS_ID = 1;
